language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build webscraping_ai.gemspec
  - gem install ./webscraping_ai-3.1.2.gem
