# -*- encoding: utf-8 -*-

=begin
#WebScraping.AI

#WebScraping.AI scraping API provides GPT-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

The version of the OpenAPI document: 3.1.3
Contact: support@webscraping.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "webscraping_ai/version"

Gem::Specification.new do |s|
  s.name        = "webscraping_ai"
  s.version     = WebScrapingAI::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["WebScraping.AI"]
  s.email       = ["hello@webscraping.ai"]
  s.homepage    = "https://webscraping.ai"
  s.summary     = "WebScraping.AI Ruby Gem"
  s.description = "WebScraping.AI scraping API provides GPT-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing."
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
