=begin
#WebScraping.AI

#WebScraping.AI scraping API provides GPT-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

The version of the OpenAPI document: 3.1.3
Contact: support@webscraping.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for WebScrapingAI::AIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AIApi' do
  before do
    # run before each test
    @api_instance = WebScrapingAI::AIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AIApi' do
    it 'should create an instance of AIApi' do
      expect(@api_instance).to be_instance_of(WebScrapingAI::AIApi)
    end
  end

  # unit tests for get_question
  # Get an answer to a question about a given web page
  # Returns the answer in plain text. Proxies and Chromium JavaScript rendering are used for page retrieval and processing, then the answer is extracted using an LLM model.
  # @param url URL of the target page.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :question Question or instructions to ask the LLM model about the target page.
  # @option opts [Integer] :context_limit Maximum number of tokens to use as context for the LLM model (4000 by default).
  # @option opts [Integer] :response_tokens Maximum number of tokens to return in the LLM model response. The total context size (context_limit) includes the question, the target page content and the response, so this parameter reserves tokens for the response (see also on_context_limit).
  # @option opts [String] :on_context_limit What to do if the context_limit parameter is exceeded (truncate by default). The context is exceeded when the target page content is too long.
  # @option opts [Hash<String, String>] :headers HTTP headers to pass to the target page. Can be specified either via a nested query parameter (...&amp;headers[One]&#x3D;value1&amp;headers&#x3D;[Another]&#x3D;value2) or as a JSON encoded object (...&amp;headers&#x3D;{\&quot;One\&quot;: \&quot;value1\&quot;, \&quot;Another\&quot;: \&quot;value2\&quot;}).
  # @option opts [Integer] :timeout Maximum web page retrieval time in ms. Increase it in case of timeout errors (10000 by default, maximum is 30000).
  # @option opts [Boolean] :js Execute on-page JavaScript using a headless browser (true by default).
  # @option opts [Integer] :js_timeout Maximum JavaScript rendering time in ms. Increase it in case if you see a loading indicator instead of data on the target page.
  # @option opts [String] :proxy Type of proxy, use residential proxies if your site restricts traffic from datacenters (datacenter by default). Note that residential proxy requests are more expensive than datacenter, see the pricing page for details.
  # @option opts [String] :country Country of the proxy to use (US by default). Only available on Startup and Custom plans.
  # @option opts [String] :device Type of device emulation.
  # @option opts [Boolean] :error_on_404 Return error on 404 HTTP status on the target page (false by default).
  # @option opts [Boolean] :error_on_redirect Return error on redirect on the target page (false by default).
  # @option opts [String] :js_script Custom JavaScript code to execute on the target page.
  # @return [String]
  describe 'get_question test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
