=begin
#WebScraping.AI

#This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for WebScrapingAI::HtmlApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HtmlApi' do
  before do
    # run before each test
    @api_instance = WebScrapingAI::HtmlApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HtmlApi' do
    it 'should create an instance of HtmlApi' do
      expect(@api_instance).to be_instance_of(WebScrapingAI::HtmlApi)
    end
  end

  # unit tests for get_page
  # Get page HTML by URL
  # @param url URL of the page to get
  # @param [Hash] opts the optional parameters
  # @return [ScrappedPage]
  describe 'get_page test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
