=begin
#WebScraping.AI

#A client for https://webscraping.ai API. It provides Chrome JS rendering, rotating proxies and HTML parsing for web scraping.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

# Common files
require 'webscraping_ai/api_client'
require 'webscraping_ai/api_error'
require 'webscraping_ai/version'
require 'webscraping_ai/configuration'

# Models
require 'webscraping_ai/models/scrapped_page'

# APIs
require 'webscraping_ai/api/html_api'

module WebScrapingAI
  class << self
    # Customize default settings for the SDK using block.
    #   WebScrapingAI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
