=begin
#WebScraping.AI

#WebScraping.AI scraping API provides LLM-powered tools with Chromium JavaScript rendering, rotating proxies, and built-in HTML parsing.

The version of the OpenAPI document: 3.2.0
Contact: support@webscraping.ai
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

# Common files
require 'webscraping_ai/api_client'
require 'webscraping_ai/api_error'
require 'webscraping_ai/version'
require 'webscraping_ai/configuration'

# Models
require 'webscraping_ai/models/account'
require 'webscraping_ai/models/error'

# APIs
require 'webscraping_ai/api/ai_api'
require 'webscraping_ai/api/account_api'
require 'webscraping_ai/api/html_api'
require 'webscraping_ai/api/selected_html_api'
require 'webscraping_ai/api/text_api'

module WebScrapingAI
  class << self
    # Customize default settings for the SDK using block.
    #   WebScrapingAI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
